try:
    print()
except Exception as e:
    print(e)